# Generated by Django 3.1.5 on 2021-09-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Up',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('signature', models.TextField()),
                ('level', models.IntegerField()),
                ('avatarUrl', models.TextField()),
                ('followerCount', models.TextField()),
                ('followingCount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('uploadTime', models.DateTimeField()),
                ('playCount', models.IntegerField()),
                ('commentCount', models.IntegerField()),
                ('bulletCommentCount', models.IntegerField()),
                ('imageUrl', models.TextField()),
                ('like', models.TextField()),
                ('coin', models.TextField()),
                ('star', models.TextField()),
                ('share', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Web.up')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tagName', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Web.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Web.video')),
            ],
        ),
    ]
